# Generated by Django 3.2.6 on 2021-08-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='share',
        ),
        migrations.RemoveField(
            model_name='article',
            name='star',
        ),
    ]
